// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddForum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddForum));
        
        string IMigrationMetadata.Id
        {
            get { return "201909241715073_AddForum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
